<a href="https://colab.research.google.com/github/israa252/Prediction-of-Product-Sales/blob/main/Project_1_Part_2_Prediction_of_Product_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prediction of Product Sales
- Author: Israa Rasheed

## Project Overview
This project involves exploring and cleaning a retail sales dataset to prepare it for analysis and predictive modeling. The dataset includes product details, store information, and sales data.  

Key steps include:  
- Inspecting the dataset structure and data types.  
- Handling missing values and removing duplicates.  
- Standardizing categorical variables.  
- Summarizing numerical features for analysis.  

The cleaned dataset is ready for further tasks such as predicting product sales.

## Load and Inspect Data

In [36]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
# Save the filepath and load the data as "df_titanic"
fpath  ="/content/drive/MyDrive/AXSOSACADEMY/01-Fundamentals/Week02/Data/sales_predictions_2023.csv"
df= pd.read_csv(fpath)
df.info()
df.head()
df.shape
df.dtypes

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

## Clean Data

In [41]:
# Drop duplicate rows
df = df.drop_duplicates()

# Check missing values
df.isnull().sum()

# Fill missing numeric values with 0
df['Item_Weight'] = df['Item_Weight'].fillna(0)

# Fill missing categorical values with 'Unknown'
df['Outlet_Size'] = df['Outlet_Size'].fillna('Unknown')

# Confirm missing values are handled
df.isnull().sum()

# Standardize text: lowercase all values in Item_Fat_Content
df['Item_Fat_Content'] = df['Item_Fat_Content'].str.lower()

# Replace inconsistent categories with consistent labels
df['Item_Fat_Content'] = df['Item_Fat_Content'].replace({
    'low fat': 'low_fat',
    'lf': 'low_fat',
    'reg': 'regular'
})

# Display summary statistic (min, max, mean of numeric columns)
df.describe().loc[['min', 'max', 'mean']]

df.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,low_fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,TIER 1,Supermarket Type1,3735.1380
1,DRC01,5.920,regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,TIER 3,Supermarket Type2,443.4228
2,FDN15,17.500,low_fat,0.016760,Meat,141.6180,OUT049,1999,Medium,TIER 1,Supermarket Type1,2097.2700
3,FDX07,19.200,regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Unknown,TIER 3,Grocery Store,732.3800
4,NCD19,8.930,low_fat,0.000000,Household,53.8614,OUT013,1987,High,TIER 3,Supermarket Type1,994.7052
5,FDP36,10.395,regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,TIER 3,Supermarket Type2,556.6088
6,FDO10,13.650,regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,TIER 3,Supermarket Type1,343.5528
7,FDP10,0.000,low_fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,TIER 3,Supermarket Type3,4022.7636
8,FDH17,16.200,regular,0.016687,Frozen Foods,96.9726,OUT045,2002,Unknown,TIER 2,Supermarket Type1,1076.5986
9,FDU28,19.200,regular,0.094450,Frozen Foods,187.8214,OUT017,2007,Unknown,TIER 2,Supermarket Type1,4710.5350

## Exploratory Data Analysis